---
- name: "Install HAproxy and update packeges"
  hosts: lb
  tasks: 
  - name: 
    yum:
      name: '*'
      state: latest
  - name: "install EPEL repo"
    become: yes
    yum: 
      name: epel-release 
      state: present

  - name: "install yum-utils"
    become: yes
    yum: 
      name: yum-utils
      state: latest  
  - name: 
    yum:
      name: haproxy
      state: latest

  - name: "Use j2 template for configure haproxy configuration file"
    template: >
      src=templates/lb/haproxy.cfg.j2
      dest=/etc/haproxy/haproxy.cfg
  
  - name: "Restart and enabled haproxy deamon"
    service:
      name: haproxy
      enabled: yes
      state: restarted
